name: Build CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build for Linux amd64
      run: GOOS=linux GOARCH=amd64 go build -v -o bin/r34-linux-amd64 cmd/main.go
    
    - name: Build for Windows amd64
      run: GOOS=windows GOARCH=amd64 go build -v -o bin/r34-windows-amd64.exe cmd/main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Build Artifacts
        path: bin/
